services:
  - type: web
    name: java-task-demo
    runtime: docker
    plan: free
    region: singapore
    branch: master
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/tasks
    autoDeploy: true
    envVars:
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx400m -XX:+UseSerialGC
      - key: APP_CORS_ALLOWED_ORIGINS
        value: https://shane360129.github.io,http://localhost:5173
